# Generated by Django 2.2.3 on 2019-11-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('course_number', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('first_day', models.CharField(max_length=10)),
                ('second_day', models.CharField(max_length=10)),
            ],
        ),
    ]
